// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUR2ifhF3dCXIKjNVpRUtyybJItr5tqw',
    appId: '1:996378770096:web:520d5a10021f9e06181975',
    messagingSenderId: '996378770096',
    projectId: 'fir-task-bea53',
    authDomain: 'fir-task-bea53.firebaseapp.com',
    storageBucket: 'fir-task-bea53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3Q3MpbAEYfbOOpmmsLSWjpBMKh-5TGc',
    appId: '1:350815746161:android:b46b2ae6bdc78a5182c3d0',
    messagingSenderId: '350815746161',
    projectId: 'ppkd-mp',
    storageBucket: 'ppkd-mp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzInhupRkc-P61JBFzgQsELx0HY_u5kQ',
    appId: '1:996378770096:ios:8eb133eb813590b4181975',
    messagingSenderId: '996378770096',
    projectId: 'fir-task-bea53',
    storageBucket: 'fir-task-bea53.firebasestorage.app',
    iosBundleId: 'com.smartresident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzInhupRkc-P61JBFzgQsELx0HY_u5kQ',
    appId: '1:996378770096:ios:8eb133eb813590b4181975',
    messagingSenderId: '996378770096',
    projectId: 'fir-task-bea53',
    storageBucket: 'fir-task-bea53.firebasestorage.app',
    iosBundleId: 'com.smartresident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCNgSZW6BYG-PPa7SL7E4MUB8uttOQH20',
    appId: '1:350815746161:web:3bf71604bbd266cf82c3d0',
    messagingSenderId: '350815746161',
    projectId: 'ppkd-mp',
    authDomain: 'ppkd-mp.firebaseapp.com',
    storageBucket: 'ppkd-mp.firebasestorage.app',
    measurementId: 'G-BPM82H0L8P',
  );

}